### ISSUE TITLE
Look at Lago (https://github.com/lago-project/lago)

### ISSUE THREAD

**Issue by mykaul** [OndrejHome/fast-vm#29]
Hi,

I bumped into this project by accident. My team developed Lago (https://github.com/lago-project/lago) and it seems to be pretty close. We have opted not to use LVM thin LVs (as it requires setup), but qcow over raw (sparse!) images, which seems like it might be an interesting project for you to compare to.

**Comment by OndrejHome** [comment]
Hi,
Thank you for information on lago, looks interesting and has quite of documentation (+1).
The reason for using LVM here was intentional and even despite of "fear to setup LVM thinpool" so far it works nice in many environments I have seen. With QCOW over sparse RAW file I'm not sure if it is possible to discard the unused space - like if it really shrinks when VM issues TRIM command (fstrim) to drive. I would have to check that out. Thank you for inspiration!

**Comment by OndrejHome** [comment]
Uff, it took me longer that expected to get to this. 

After several attempts I was mostly unsuccessful in getting the lago running on CentOS 7.3/7.4. 
I have tried following the documentation - http://lago.readthedocs.io/en/latest/Installation.html
I was using a minimal installation (as selected in installer) of CentOS and trying to run everything as user root - most common scenario for my testing systems.
Issues I have hit:
- missing command pip (ok, installed the `python2-pip` package)
- seems that this is for python 3 (this is not a default python in CentOS that uses 2.7) - so the `pip install lago` fails with error ending with `    distutils.errors.DistutilsError: Setup script exited with error in cryptography setup command: Invalid environment marker: python_version < '3'`
- with python3 the pip3 installation finished but resulting in non-working command (module utils missing)

So trying out installation via RPM (successful), I have tried also the http://lago.readthedocs.io/en/latest/Jenkins_Example.html
- when the libvirt is not running the error message from `lago init` is a python trace - might be nicer to just tell me to not try running it when libvirtd is stopped/unresponsive
- running as root I also get some permission denied because of the place where data are stored (`chmod o+x /root` solves this) - this has a nicer message explaining why error occured
- here I was able to get the VMs from lago-demo repo running and I can connect to shell

Some thoughts from initial runs:
- I can list machines from some lago project if I know in which directory to execute the `lago status` (a bit inconvenient when I just wanna know what machines I have and not how I have set them up - need to remember the directory and ideally not loose it)
- trying to get around I would like to have some man page but both `lago` and `lagocli` seems to not provide any, there is output from commands when no argument is passed but it doesn't give me a hint on what I can use (`lago --help` is much more useful)
- no bash completion to make my life easier
- having a copr (https://copr.fedorainfracloud.org/) repository might be a nice thing for RPMs and easy updates compared to current repository
- I like that it can automatically download the images when they are not present on system
- when the VMs are stopped I need to have a directory with lago project to find them

I may check later on this for some further comparison to see how this behaves on multi user systems where the data will be shared.

Above is just free form feedback from my testings done so far when getting familiar with lago. My biggest concern why this wouldn't be my tool of choice is that if I loose the directory with VM images and definitions, then VMs are gone - with fast-vm I somehow expect that everything is in LVM that is system-wide and VMs are defined while their data disks in LVM exists. Here they are created more on-demand.

**Comment by OndrejHome** [comment]
Honestly I didn't have more time to look through this. fast-vm still makes sense to me as it doesn't depend on any python as of now an therefore I would like to keep it as alternative in that way.
For people that are unsure if fast-vm is for them and that would like to know about some other projects that are similar I have added link to Lago project in README (commit 53c83e8b007ac7e426d5cf372dd1015a90b24704).
Thank you @mykaul for bringing this to my attention. I will close this issue now.
